name: farfor_test_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation package
  go_router: ^6.5.8

  # Data packages
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  retrofit: ^4.0.1
  cached_network_image: ^3.2.3
  json_annotation: ^4.7.0

  # DI
  get_it: ^7.3.0

  # State managment packages
  flutter_bloc: ^8.1.2
  provider: ^6.0.5

  # Localization
  easy_localization: ^3.0.1

  # UI packages
  flutter_svg: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  retrofit_generator: ^6.0.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: raleway_extraBold
      fonts:
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
    - family: raleway_regular
      fonts:
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
    - family: raleway_semiBold
      fonts:
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf

     

  